version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

defaults: &defaults
  docker:
    - image: circleci/node:latest

commands:
  print_file:
    description: "Using Parameters to make code modular - using commands"
    parameters:
      filename:
        type: string
        default: "~/output.txt"
    steps:
      - run: cat << parameters.filename >>

jobs:
  test_env_vars:
    <<: *defaults
    steps:
      - checkout
      - run: curl https://kvdb.io/DGe9gM4CFk6q6CJZA5sNr/Hello-world > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - print_file

  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install && npm run test

  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm install && npm run build

  audit:
    <<: *defaults
    steps:
      - checkout
      - run: npm install && npm audit

workflows:
  Example-workflow:
    jobs:
      - audit
      - test_env_vars
      - test
      - print_output_file:
          requires:
            - test_env_vars
      - build:
          requires:
            - audit
