version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

defaults: &defaults
  docker:
    - image: circleci/node:latest

commands:
  destroy_infra:
    steps:
      - run:
          name: destroy infrastructure
          when: on_fail
          command: aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}

jobs:

  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install && npm run test
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run build

  analyze:
    <<: *defaults
    steps:
      - checkout
      - run: npm audit
      - run:
          name: Analyze
          command: echo "This is a security risk, notify the engineering team"
          when: on_fail

  configure_infra:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys: 
          fingureprints:
            - "03:d9:56:83:f5:02:fc:de:e8:56:56:36:20:60:fc:58"
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Install tar utility
          command: |
            apk add --update tar gzip
      - run:
          name: Install deps
          command: |
            apk add --update --no-cache ansible
      - attach_workspace:
          at: .
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt ansible/main.yml --key-file ~/.ssh/id_rsa_03d95683f502fcdee85656362060fc58

  create_infra: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file infra/template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region ${AWS_DEFAULT_REGION}
      - run:
          name: Get the IP
          command: |
            echo [ubuntu] > inventory.txt &&
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --output text >> inventory.txt && cat inventory.txt
      - persist_to_workspace:
          root: .
          paths:
            - inventory.txt
      - destroy_infra

  smoke_test:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: smoke test simulation
          command: |
            if curl -s --head "https://faked33google.com"
            then
              echo "It worked"
            else
              echo "It failed"
            fi
      - destroy_infra

workflows:

  udacity:
    jobs:
      - test
      - build:
          requires:
            - test
      - create_infra:
          requires:
            - build
      - configure_infra:
          requires:
            - create_infra
      - smoke_test:
          requires:
            - configure_infra
