version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:

  test_env_vars:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "This is my name echoed below!!!"
          command: |
            echo $MY_NAME

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: run commands
          command: |
            npm install &&
            npm run test

  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: build commands
          command: |
            npm install &&
            npm run build

  audit:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Run Audit
          command: |
            npm install &&
            npm audit

workflows:
  Example-workflow:
    jobs:
      - audit
      - test_env_vars
      - test
      - build:
          requires:
            - audit
